name: POC Local Test

on:
  workflow_dispatch:
  push:
    branches:
      - feat/POC

jobs:
  poc:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run InstantRelease POC
        uses: ./poc-action
        with:
          generate-changelog: true
          create-tags: true
          dry-run: false
          strict-dry-run: false
          debug: false
          